GET http://localhost:5000/products

###
GET http://localhost:5000/products/1

###
POST http://localhost:5000/products
Content-Type: application/json

{
   "name": "Apple Iphone 12 Mini",
   "price": 1000
}

###
PATCH http://localhost:5000/products/1
Content-Type: application/json

{
   "name": "Apple Iphone X",
   "price": 799
}


###
DELETE http://localhost:5000/products/1